import { Request, ResponseToolkit } from "@hapi/hapi";

/**
 * This file is automatically generated from swagger.  It is safe to overwrite an existing file with this one.
 *
 * This file defines the interface that the AddressesController must conform to.  This helps the Typescript
 * compiler to alert the developer when the swagger specification for methods covered by this controller have changed, and the
 * developer needs to make changes to the implementation in order to support the updated API.
 */
interface IAddressesController {



  /**
  * Get all address
  */
  public async getAddresses(request: Request, toolkit: ResponseToolkit);

  /**
  * Add a new address to the system
  */
  public async addAddress(request: Request, toolkit: ResponseToolkit);

  /**
  * Find address by ID
  */
  public async getAddressById(request: Request, toolkit: ResponseToolkit);

  /**
  * Update an existing address
  */
  public async updateAddress(request: Request, toolkit: ResponseToolkit);

  /**
  * Delete a address
  */
  public async deleteAddress(request: Request, toolkit: ResponseToolkit);

}

export { IAddressesController }
