import { Request, ResponseToolkit } from "@hapi/hapi";

/**
 * This file is automatically generated from swagger.  It is safe to overwrite an existing file with this one.
 *
 * This file defines the interface that the CarsController must conform to.  This helps the Typescript
 * compiler to alert the developer when the swagger specification for methods covered by this controller have changed, and the
 * developer needs to make changes to the implementation in order to support the updated API.
 */
interface ICarsController {



  /**
  * Get all car
  */
  public async getCars(request: Request, toolkit: ResponseToolkit);

  /**
  * Add a new car to the system
  */
  public async addCar(request: Request, toolkit: ResponseToolkit);

  /**
  * Find car by ID
  */
  public async getCarById(request: Request, toolkit: ResponseToolkit);

  /**
  * Update an existing car
  */
  public async updateCar(request: Request, toolkit: ResponseToolkit);

  /**
  * Delete a car
  */
  public async deleteCar(request: Request, toolkit: ResponseToolkit);

  /**
  * All race results for that car
  */
  public async getRaceResultsByCarId(request: Request, toolkit: ResponseToolkit);

}

export { ICarsController }
