import { Request, ResponseToolkit } from "@hapi/hapi";

/**
 * This file is automatically generated from swagger.  It is safe to overwrite an existing file with this one.
 *
 * This file defines the interface that the DriversController must conform to.  This helps the Typescript
 * compiler to alert the developer when the swagger specification for methods covered by this controller have changed, and the
 * developer needs to make changes to the implementation in order to support the updated API.
 */
interface IDriversController {



  /**
  * Get all driver
  */
  public async getDrivers(request: Request, toolkit: ResponseToolkit);

  /**
  * Add a new driver to the system
  */
  public async addDriver(request: Request, toolkit: ResponseToolkit);

  /**
  * Find driver by ID
  */
  public async getDriverById(request: Request, toolkit: ResponseToolkit);

  /**
  * Update an existing driver
  */
  public async updateDriver(request: Request, toolkit: ResponseToolkit);

  /**
  * Delete a driver
  */
  public async deleteDriver(request: Request, toolkit: ResponseToolkit);

  /**
  * All race results for that driver
  */
  public async getRaceResultsByDriverId(request: Request, toolkit: ResponseToolkit);

}

export { IDriversController }
