import { Request, ResponseToolkit } from "@hapi/hapi";

/**
 * This file is automatically generated from swagger.  It is safe to overwrite an existing file with this one.
 *
 * This file defines the interface that the RacesController must conform to.  This helps the Typescript
 * compiler to alert the developer when the swagger specification for methods covered by this controller have changed, and the
 * developer needs to make changes to the implementation in order to support the updated API.
 */
interface IRacesController {



  /**
  * Get all race
  */
  public async getRaces(request: Request, toolkit: ResponseToolkit);

  /**
  * Add a new race to the system
  */
  public async addRace(request: Request, toolkit: ResponseToolkit);

  /**
  * Find race by ID
  */
  public async getRaceById(request: Request, toolkit: ResponseToolkit);

  /**
  * Update an existing race
  */
  public async updateRace(request: Request, toolkit: ResponseToolkit);

  /**
  * Delete a race
  */
  public async deleteRace(request: Request, toolkit: ResponseToolkit);

  /**
  * All race results for that race
  */
  public async getRaceResultsByRaceId(request: Request, toolkit: ResponseToolkit);

  /**
  * Add race results for that race
  */
  public async addRaceResults(request: Request, toolkit: ResponseToolkit);

}

export { IRacesController }
