import { Request, ResponseToolkit } from "@hapi/hapi";

/**
 * This file is automatically generated from swagger.  It is safe to overwrite an existing file with this one.
 *
 * This file defines the interface that the TeamsController must conform to.  This helps the Typescript
 * compiler to alert the developer when the swagger specification for methods covered by this controller have changed, and the
 * developer needs to make changes to the implementation in order to support the updated API.
 */
interface ITeamsController {



  /**
  * Get all team
  */
  public async getTeams(request: Request, toolkit: ResponseToolkit);

  /**
  * Add a new team to the system
  */
  public async addTeam(request: Request, toolkit: ResponseToolkit);

  /**
  * Find team by ID
  */
  public async getTeamById(request: Request, toolkit: ResponseToolkit);

  /**
  * Update an existing team
  */
  public async updateTeam(request: Request, toolkit: ResponseToolkit);

  /**
  * Delete a team
  */
  public async deleteTeam(request: Request, toolkit: ResponseToolkit);

}

export { ITeamsController }
